DATASET:
    train_list: ['Human36M']
    test_list: ['Human36M']
    input_joint_set: 'human36'
    target_joint_set: 'human36'
    workers: 16
    use_gt_input: False

MODEL:
    name: 'posenet'
    input_shape: [384, 288]

TRAIN:
    print_freq: 10
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 60
    scheduler: 'step'
    lr: 0.0005
    lr_step: [10, 20, 30, 40, 50]
    lr_factor: 0.2
    optimizer: 'adam'

AUG:
    flip: True
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False