DATASET:
    train_list: ['Human36M']
    test_list: ['Human36M']
    input_joint_set: 'human36'
    target_joint_set: 'human36'
    workers: 16
    use_gt_input: False

MODEL:
    name: 'pose2mesh_net'
    input_shape: [384, 288]
    normal_loss_weight: 0.01
    edge_loss_weight: 0.1
    joint_loss_weight: 0.001
    posenet_pretrained: True
    posenet_path: './experiment/chev/checkpoint/best.pth.tar'

TRAIN:
    print_freq: 10
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 60
    edge_loss_start: 7
    scheduler: 'step'
    lr: 0.0001
    lr_step: [10, 20, 30, 40, 50]
    lr_factor: 0.5
    optimizer: 'adam'

AUG:
    flip: False
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False
